# cloudbuild.yaml
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - gcloud
    - functions
    - deploy
    - imginfo-makemodel-v2 # ユニークなFunction名
    - --source=.
    - --runtime=python311
    - --trigger-http
    - --allow-unauthenticated
    - --entry-point=makemodel # main.pyの関数名 (def makemodel(request):)
    - --region=asia-northeast1
    # ★★★ ここを修正 ★★★
    - --set-env-vars=GCS_BUCKET_NAME=model-raw-img,GCS_OUTPUT_BUCKET_NAME=model-output-urls # ★GCS_OUTPUT_BUCKET_NAMEを追加し、正しいバケット名に置き換える
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET